use "pony_test"
use "pony_check"
use "../protobuf"

actor \nodoc\ Main is TestList
  new create(env: Env) =>
    PonyTest(env, this)

  fun tag tests(test: PonyTest) =>
    test(_TestVarintEncodeOne)
    test(_TestVarintEncodeOneFifty)
    test(_TestVarintEncodeThreeHundred)
    test(_TestVarintEncodeMax)
    test(_TestVarintDecodeOneFifty)
    test(_TestVarintDecodeTruncated)
    test(_TestVarintDecodeOverflow)
    test(_TestVarintDecodeEmpty)
    test(_TestZigZagEncodeKnown)
    test(_TestZigZagDecodeKnown)
    test(_TestTagEncodedValue)
    test(_TestTagDecodeRoundTrip)
    test(_TestTagDecodeZeroFieldRejected)
    test(_TestTagDecodeUnknownWireType)
    test(Property1UnitTest[U64](_PropVarintRoundTrip))
    test(Property1UnitTest[I64](_PropZigZagI64RoundTrip))
    test(Property1UnitTest[I32](_PropZigZagI32RoundTrip))
    test(Property1UnitTest[U32](_PropTagRoundTrip))
    test(_TestLEU32EncodeKnown)
    test(_TestLEU32DecodeKnown)
    test(_TestLEU32DecodeTruncated)
    test(_TestFloatOneEncoded)
    test(_TestDoubleOneEncoded)
    test(_TestStringHelloEncoded)
    test(_TestReaderAtEnd)
    test(_TestReaderSkipVarint)
    test(_TestReaderSkipFixed64)
    test(_TestReaderSkipFixed32)
    test(_TestReaderSkipLenDelim)
    test(_TestReaderSkipFixed64Truncated)
    test(_TestReadStringValid)
    test(_TestReadStringValidMultibyte)
    test(_TestReadStringInvalidUtf8Lead)
    test(_TestReadStringInvalidUtf8Truncated)
    test(_TestReadStringOverlong)
    test(_TestReadStringSurrogate)
    test(_TestLenDelimRoundTrip)
    test(_TestLenDelimEmpty)
    test(Property1UnitTest[Bool](_PropBoolRoundTrip))
    test(Property1UnitTest[I32](_PropInt32RoundTrip))
    test(Property1UnitTest[I64](_PropInt64RoundTrip))
    test(Property1UnitTest[U32](_PropUint32RoundTrip))
    test(Property1UnitTest[U64](_PropUint64RoundTrip))
    test(Property1UnitTest[I32](_PropSint32RoundTrip))
    test(Property1UnitTest[I64](_PropSint64RoundTrip))
    test(Property1UnitTest[U32](_PropFixed32RoundTrip))
    test(Property1UnitTest[U64](_PropFixed64RoundTrip))
    test(Property1UnitTest[I32](_PropSfixed32RoundTrip))
    test(Property1UnitTest[I64](_PropSfixed64RoundTrip))
    test(Property1UnitTest[U32](_PropFloatRoundTrip))
    test(Property1UnitTest[U64](_PropDoubleRoundTrip))
    test(Property1UnitTest[Array[U8]](_PropFuzzReadVarint))
    test(Property1UnitTest[Array[U8]](_PropFuzzReadTag))
    test(Property1UnitTest[Array[U8]](_PropFuzzReadString))
